# Site settings
title: Sampson Lau
email: sl2427@cornell.edu
url: http://sampsonlau.com
description: "Chemical engineer, scientist, and b-boy."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Sampson Lau

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/sampsonlau
  - title: researchgate
    url: https://www.researchgate.net/profile/Sampson_Lau

# Build settings
markdown: kramdown
permalink: pretty
